debugging web server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
 
 # Check if the correct number of parameters is provided
-if [ "$#" -ne 4 ]; then
+if [ "$#" -lt 4 ]; then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-# Assign parameters to variables
-path_to_file="$1"
-ip="$2"
-username="$3"
-ssh_key="$4"
+# Use scp to transfer the file to the server's home directory
+scp -i "$4" "$1" "$3@$2":~/
 
-scp -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$4" "$1" "$3@$2":~/
+# Check the exit status of the scp command
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully."
+else
+    echo "File transfer failed."
+fi
